spring.datasource.url=jdbc:postgresql://postgres:5432/postgres_db
spring.data.redis.host=redis
minio.endpoint.url=${MINIO_URL}

logging.file.name=/app/logs/cloud-file-storage.log
logging.charset.console=UTF-8
logging.threshold.console=INFO
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{40} - %msg%n
logging.logback.rollingpolicy.file-name-pattern=/app/logs/archive/cloud-file-storage.%d{yyyy-MM-dd}.%i.log.gz
logging.logback.rollingpolicy.max-history=14
logging.logback.rollingpolicy.total-size-cap=500MB