# split application.properties into different configs: dev, prod, test
spring.application.name=CloudFileStorage
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5430/postgres_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD:redis}
spring.session.timeout=2h

minio.endpoint.url=${MINIO_URL}
minio.access-key=${MINIO_USER}
minio.secret-key=${MINIO_PASSWORD}
minio.bucket=user-files
minio.prefix.template=user-%s-files/

logging.file.name=logs/cloudFileStorage.log
logging.level.org.springdoc=ERROR