spring.datasource.url=jdbc:postgresql://localhost:5430/postgres_db
spring.data.redis.host=localhost
minio.endpoint.url=${MINIO_URL:http://localhost:9000}

logging.level.io.github.XanderGI=DEBUG
logging.charset.console=UTF-8
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) %clr([%thread]){magenta} %clr(%logger{40}){cyan} - %msg%n